import type {
  Callback,
  IdentityBinaryCallback,
  IdentityBinaryCurried,
  IdentityCallback,
  IdentityMapCallback,
  IdentityNaryCurried,
  MapCallback,
  NumberBinaryCallback,
  NumberBinaryCurried,
  NumberCallback,
  NumberMapCallback,
  NumberNaryCurried,
  ReduceCallback,
} from './functions'
import { identity } from './functions'
import { map, reduce } from './iteration'
import {
  add,
  ceiling,
  decrement,
  divide,
  exponentiate,
  floor,
  increment,
  multiply,
  negate,
  reciprocal,
  remainder,
  subtract,
} from './math'
import { isNumber, isString } from './typePredicates'

export {
  add,
  Callback,
  ceiling,
  decrement,
  divide,
  exponentiate,
  identity,
  IdentityBinaryCallback,
  IdentityBinaryCurried,
  IdentityCallback,
  IdentityMapCallback,
  IdentityNaryCurried,
  increment,
  isNumber,
  isString,
  floor,
  map,
  multiply,
  negate,
  MapCallback,
  NumberBinaryCallback,
  NumberBinaryCurried,
  NumberCallback,
  NumberMapCallback,
  NumberNaryCurried,
  reciprocal,
  reduce,
  ReduceCallback,
  remainder,
  subtract,
}
